[build]
  publish = "exampleSite/public"
  command = "cd exampleSite && hugo --gc --minify --themesDir ../.."
  
[build.environment]
  HUGO_VERSION = "0.81.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"